name: Schedule Heroku Dyno

on:
  schedule:
    - cron: '*/1 * * * *'  # Adjust the cron expression to your schedule (e.g., every hour)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scale-dyno:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run scheduler script
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DYNO_TYPE: web
          DYNO_QUANTITY: 1
        run: node scheduler.js
